### ISSUE TITLE
Display Change when touching D8 Cable

### ISSUE THREAD

**Issue by D-G-L** [netdata-be/nitrox_analyser#2]
Hi, I built up the Analyzer, works fine, but somehow the display changes everytime I just touch cable from D8 (Pushbutton connection to Arduino) even if its not even connected. It happens also when I even plug in the cable to D8.
I assume some shortcuts?

**Comment by netdata-be** [comment]
This is indeed a bug, I need to use the `INPUT_PULLUP` now I'm using `INPUT` which gives this random triggers when touching wires.

https://github.com/netdata-be/nitrox_analyser/blob/fcae7c56173c17c7ffadd6d22ad42e6ab7f131c3/nitrox_analyzer.ino#L174-L176

However this means that I should invert the behaviour as well.
I will try to fix this later this week.

Thanks for reporting.

**Comment by D-G-L** [comment]
Just for info: Changing just to INPUT_PULLUP now starts a calibrating when you touch the button. If you touch it again fast after that, it changes the display as it should. But every new touch first starts calibrating. Try to work also through it TKS

**Comment by netdata-be** [comment]
Indeed that is the behaviour I would expect, since changing to `INPUT_PULLUP`  inverts the Behaviour of the button.
To sum:

`INPUT`
* Button not pressed => LOW
* Button pressed => HIGH

`INPUT_PULLUP`
* Button not pressed => High
* Button pressed => LOW

So the logic that detects the button press needs to inverted as well.

You can do that if you want and submit a Pull request, or I can do this later this week.

**Comment by D-G-L** [comment]
Code changed, works now

**Comment by netdata-be** [comment]
Thanks for the PR, I will link them so there is tracking.
